/*
 * generated by Xtext
 */
package fr.mines_nantes.atlanmod.dsl.ui.contentassist

import fr.mines_nantes.atlanmod.dsl.ui.contentassist.AbstractGiraffeDSLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GiraffeDSLProposalProvider extends AbstractGiraffeDSLProposalProvider {
}
