/*
 * generated by Xtext
 */
package fr.mines_nantes.atlanmod.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GiraffeDSLRuntimeModule extends fr.mines_nantes.atlanmod.dsl.AbstractGiraffeDSLRuntimeModule {

}
