/*
 * generated by Xtext
 */
package fr.mines_nantes.atlanmod.giraffe.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GiraffeDSLUiModule extends fr.mines_nantes.atlanmod.giraffe.ui.AbstractGiraffeDSLUiModule {
	public GiraffeDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
