/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {
	
	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getVirtualMachineTypeFeatureAccess().getTypeAlternatives_3_0(), "rule__VirtualMachineTypeFeature__TypeAlternatives_3_0");
					put(grammarAccess.getCloudOptionalTypesAccess().getAlternatives(), "rule__CloudOptionalTypes__Alternatives");
					put(grammarAccess.getCloudTypeAccess().getTypeAlternatives_3_0(), "rule__CloudType__TypeAlternatives_3_0");
					put(grammarAccess.getMonitoringTypeAccess().getTypeAlternatives_3_0(), "rule__MonitoringType__TypeAlternatives_3_0");
					put(grammarAccess.getCreateAccess().getGroup(), "rule__Create__Group__0");
					put(grammarAccess.getInitMachinesFeatureAccess().getGroup(), "rule__InitMachinesFeature__Group__0");
					put(grammarAccess.getInitIncrementFeatureAccess().getGroup(), "rule__InitIncrementFeature__Group__0");
					put(grammarAccess.getVirtualMachineFeatureAccess().getGroup(), "rule__VirtualMachineFeature__Group__0");
					put(grammarAccess.getVirtualMachineAccess().getGroup(), "rule__VirtualMachine__Group__0");
					put(grammarAccess.getVirtualMachineTypeFeatureAccess().getGroup(), "rule__VirtualMachineTypeFeature__Group__0");
					put(grammarAccess.getCloudProviderTypeAccess().getGroup(), "rule__CloudProviderType__Group__0");
					put(grammarAccess.getCloudProviderAccess().getGroup(), "rule__CloudProvider__Group__0");
					put(grammarAccess.getCloudTypeAccess().getGroup(), "rule__CloudType__Group__0");
					put(grammarAccess.getScriptTypeAccess().getGroup(), "rule__ScriptType__Group__0");
					put(grammarAccess.getGeoZoneTypeAccess().getGroup(), "rule__GeoZoneType__Group__0");
					put(grammarAccess.getMgmAddressTypeAccess().getGroup(), "rule__MgmAddressType__Group__0");
					put(grammarAccess.getCloudCredentialTypeAccess().getGroup(), "rule__CloudCredentialType__Group__0");
					put(grammarAccess.getCloudUserTypeAccess().getGroup(), "rule__CloudUserType__Group__0");
					put(grammarAccess.getCloudPasswordTypeAccess().getGroup(), "rule__CloudPasswordType__Group__0");
					put(grammarAccess.getDeployAccess().getGroup(), "rule__Deploy__Group__0");
					put(grammarAccess.getDeployAppFeatureAccess().getGroup(), "rule__DeployAppFeature__Group__0");
					put(grammarAccess.getDeployTypeFeatureAccess().getGroup(), "rule__DeployTypeFeature__Group__0");
					put(grammarAccess.getDeployTypeAccess().getGroup(), "rule__DeployType__Group__0");
					put(grammarAccess.getDeployRangeTypeAccess().getGroup(), "rule__DeployRangeType__Group__0");
					put(grammarAccess.getDeployAppAccess().getGroup(), "rule__DeployApp__Group__0");
					put(grammarAccess.getDeployAppClassTypeAccess().getGroup(), "rule__DeployAppClassType__Group__0");
					put(grammarAccess.getDeployAppMasterMethodTypeAccess().getGroup(), "rule__DeployAppMasterMethodType__Group__0");
					put(grammarAccess.getDeployAppSlaveMethodTypeAccess().getGroup(), "rule__DeployAppSlaveMethodType__Group__0");
					put(grammarAccess.getMonitorAccess().getGroup(), "rule__Monitor__Group__0");
					put(grammarAccess.getMonitorRangeTypeAccess().getGroup(), "rule__MonitorRangeType__Group__0");
					put(grammarAccess.getMonitoringTypeAccess().getGroup(), "rule__MonitoringType__Group__0");
					put(grammarAccess.getStressAccess().getGroup(), "rule__Stress__Group__0");
					put(grammarAccess.getStressRangeTypeAccess().getGroup(), "rule__StressRangeType__Group__0");
					put(grammarAccess.getStressClassTypeAccess().getGroup(), "rule__StressClassType__Group__0");
					put(grammarAccess.getStressMethodTypeAccess().getGroup(), "rule__StressMethodType__Group__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionRangeTypeAccess().getGroup(), "rule__ActionRangeType__Group__0");
					put(grammarAccess.getActionClassTypeAccess().getGroup(), "rule__ActionClassType__Group__0");
					put(grammarAccess.getActionMethodTypeAccess().getGroup(), "rule__ActionMethodType__Group__0");
					put(grammarAccess.getFeaturesAccess().getGroup(), "rule__Features__Group__0");
					put(grammarAccess.getIntFeatureAccess().getGroup(), "rule__IntFeature__Group__0");
					put(grammarAccess.getDomainModelAccess().getElementsAssignment(), "rule__DomainModel__ElementsAssignment");
					put(grammarAccess.getCreateAccess().getNameAssignment_1(), "rule__Create__NameAssignment_1");
					put(grammarAccess.getCreateAccess().getVMachineAssignment_3(), "rule__Create__VMachineAssignment_3");
					put(grammarAccess.getCreateAccess().getInitMachinesAssignment_4(), "rule__Create__InitMachinesAssignment_4");
					put(grammarAccess.getCreateAccess().getInitIncrementAssignment_5(), "rule__Create__InitIncrementAssignment_5");
					put(grammarAccess.getInitMachinesFeatureAccess().getManyAssignment_0(), "rule__InitMachinesFeature__ManyAssignment_0");
					put(grammarAccess.getInitMachinesFeatureAccess().getNameAssignment_1(), "rule__InitMachinesFeature__NameAssignment_1");
					put(grammarAccess.getInitMachinesFeatureAccess().getTypeAssignment_3(), "rule__InitMachinesFeature__TypeAssignment_3");
					put(grammarAccess.getInitIncrementFeatureAccess().getManyAssignment_0(), "rule__InitIncrementFeature__ManyAssignment_0");
					put(grammarAccess.getInitIncrementFeatureAccess().getNameAssignment_1(), "rule__InitIncrementFeature__NameAssignment_1");
					put(grammarAccess.getInitIncrementFeatureAccess().getTypeAssignment_3(), "rule__InitIncrementFeature__TypeAssignment_3");
					put(grammarAccess.getVirtualMachineFeatureAccess().getManyAssignment_0(), "rule__VirtualMachineFeature__ManyAssignment_0");
					put(grammarAccess.getVirtualMachineFeatureAccess().getNameAssignment_1(), "rule__VirtualMachineFeature__NameAssignment_1");
					put(grammarAccess.getVirtualMachineFeatureAccess().getTypeAssignment_3(), "rule__VirtualMachineFeature__TypeAssignment_3");
					put(grammarAccess.getVirtualMachineAccess().getNameAssignment_1(), "rule__VirtualMachine__NameAssignment_1");
					put(grammarAccess.getVirtualMachineAccess().getVMAssignment_3(), "rule__VirtualMachine__VMAssignment_3");
					put(grammarAccess.getVirtualMachineAccess().getCloudProviderAssignment_4(), "rule__VirtualMachine__CloudProviderAssignment_4");
					put(grammarAccess.getVirtualMachineTypeFeatureAccess().getManyAssignment_0(), "rule__VirtualMachineTypeFeature__ManyAssignment_0");
					put(grammarAccess.getVirtualMachineTypeFeatureAccess().getNameAssignment_1(), "rule__VirtualMachineTypeFeature__NameAssignment_1");
					put(grammarAccess.getVirtualMachineTypeFeatureAccess().getTypeAssignment_3(), "rule__VirtualMachineTypeFeature__TypeAssignment_3");
					put(grammarAccess.getCloudProviderTypeAccess().getManyAssignment_0(), "rule__CloudProviderType__ManyAssignment_0");
					put(grammarAccess.getCloudProviderTypeAccess().getNameAssignment_1(), "rule__CloudProviderType__NameAssignment_1");
					put(grammarAccess.getCloudProviderTypeAccess().getTypeAssignment_3(), "rule__CloudProviderType__TypeAssignment_3");
					put(grammarAccess.getCloudProviderAccess().getNameAssignment_1(), "rule__CloudProvider__NameAssignment_1");
					put(grammarAccess.getCloudProviderAccess().getCloudTypeAssignment_3(), "rule__CloudProvider__CloudTypeAssignment_3");
					put(grammarAccess.getCloudProviderAccess().getCloudAddressAssignment_4(), "rule__CloudProvider__CloudAddressAssignment_4");
					put(grammarAccess.getCloudProviderAccess().getCloudCredentialAssignment_5(), "rule__CloudProvider__CloudCredentialAssignment_5");
					put(grammarAccess.getCloudProviderAccess().getCloudOptionalTypesAssignment_6(), "rule__CloudProvider__CloudOptionalTypesAssignment_6");
					put(grammarAccess.getCloudTypeAccess().getManyAssignment_0(), "rule__CloudType__ManyAssignment_0");
					put(grammarAccess.getCloudTypeAccess().getNameAssignment_1(), "rule__CloudType__NameAssignment_1");
					put(grammarAccess.getCloudTypeAccess().getTypeAssignment_3(), "rule__CloudType__TypeAssignment_3");
					put(grammarAccess.getScriptTypeAccess().getManyAssignment_0(), "rule__ScriptType__ManyAssignment_0");
					put(grammarAccess.getScriptTypeAccess().getNameAssignment_1(), "rule__ScriptType__NameAssignment_1");
					put(grammarAccess.getScriptTypeAccess().getTypeAssignment_3(), "rule__ScriptType__TypeAssignment_3");
					put(grammarAccess.getGeoZoneTypeAccess().getManyAssignment_0(), "rule__GeoZoneType__ManyAssignment_0");
					put(grammarAccess.getGeoZoneTypeAccess().getNameAssignment_1(), "rule__GeoZoneType__NameAssignment_1");
					put(grammarAccess.getGeoZoneTypeAccess().getTypeAssignment_3(), "rule__GeoZoneType__TypeAssignment_3");
					put(grammarAccess.getMgmAddressTypeAccess().getManyAssignment_0(), "rule__MgmAddressType__ManyAssignment_0");
					put(grammarAccess.getMgmAddressTypeAccess().getNameAssignment_1(), "rule__MgmAddressType__NameAssignment_1");
					put(grammarAccess.getMgmAddressTypeAccess().getTypeAssignment_3(), "rule__MgmAddressType__TypeAssignment_3");
					put(grammarAccess.getCloudCredentialTypeAccess().getManyAssignment_0(), "rule__CloudCredentialType__ManyAssignment_0");
					put(grammarAccess.getCloudCredentialTypeAccess().getNameAssignment_1(), "rule__CloudCredentialType__NameAssignment_1");
					put(grammarAccess.getCloudCredentialTypeAccess().getTypeAssignment_3(), "rule__CloudCredentialType__TypeAssignment_3");
					put(grammarAccess.getCloudUserTypeAccess().getManyAssignment_0(), "rule__CloudUserType__ManyAssignment_0");
					put(grammarAccess.getCloudUserTypeAccess().getNameAssignment_1(), "rule__CloudUserType__NameAssignment_1");
					put(grammarAccess.getCloudUserTypeAccess().getTypeAssignment_3(), "rule__CloudUserType__TypeAssignment_3");
					put(grammarAccess.getCloudPasswordTypeAccess().getManyAssignment_0(), "rule__CloudPasswordType__ManyAssignment_0");
					put(grammarAccess.getCloudPasswordTypeAccess().getNameAssignment_1(), "rule__CloudPasswordType__NameAssignment_1");
					put(grammarAccess.getCloudPasswordTypeAccess().getTypeAssignment_3(), "rule__CloudPasswordType__TypeAssignment_3");
					put(grammarAccess.getDeployAccess().getNameAssignment_1(), "rule__Deploy__NameAssignment_1");
					put(grammarAccess.getDeployAccess().getDeployOneAssignment_3(), "rule__Deploy__DeployOneAssignment_3");
					put(grammarAccess.getDeployAccess().getDeployTwoAssignment_4(), "rule__Deploy__DeployTwoAssignment_4");
					put(grammarAccess.getDeployAppFeatureAccess().getManyAssignment_0(), "rule__DeployAppFeature__ManyAssignment_0");
					put(grammarAccess.getDeployAppFeatureAccess().getNameAssignment_1(), "rule__DeployAppFeature__NameAssignment_1");
					put(grammarAccess.getDeployAppFeatureAccess().getTypeAssignment_3(), "rule__DeployAppFeature__TypeAssignment_3");
					put(grammarAccess.getDeployTypeFeatureAccess().getManyAssignment_0(), "rule__DeployTypeFeature__ManyAssignment_0");
					put(grammarAccess.getDeployTypeFeatureAccess().getNameAssignment_1(), "rule__DeployTypeFeature__NameAssignment_1");
					put(grammarAccess.getDeployTypeFeatureAccess().getTypeAssignment_3(), "rule__DeployTypeFeature__TypeAssignment_3");
					put(grammarAccess.getDeployTypeAccess().getNameAssignment_1(), "rule__DeployType__NameAssignment_1");
					put(grammarAccess.getDeployTypeAccess().getRangeAssignment_3(), "rule__DeployType__RangeAssignment_3");
					put(grammarAccess.getDeployRangeTypeAccess().getManyAssignment_0(), "rule__DeployRangeType__ManyAssignment_0");
					put(grammarAccess.getDeployRangeTypeAccess().getNameAssignment_1(), "rule__DeployRangeType__NameAssignment_1");
					put(grammarAccess.getDeployRangeTypeAccess().getTypeAssignment_3(), "rule__DeployRangeType__TypeAssignment_3");
					put(grammarAccess.getDeployAppAccess().getNameAssignment_1(), "rule__DeployApp__NameAssignment_1");
					put(grammarAccess.getDeployAppAccess().getClassAssignment_3(), "rule__DeployApp__ClassAssignment_3");
					put(grammarAccess.getDeployAppAccess().getDeployMasterMethodAssignment_4(), "rule__DeployApp__DeployMasterMethodAssignment_4");
					put(grammarAccess.getDeployAppAccess().getDeploySlaveMethodAssignment_5(), "rule__DeployApp__DeploySlaveMethodAssignment_5");
					put(grammarAccess.getDeployAppClassTypeAccess().getManyAssignment_0(), "rule__DeployAppClassType__ManyAssignment_0");
					put(grammarAccess.getDeployAppClassTypeAccess().getNameAssignment_1(), "rule__DeployAppClassType__NameAssignment_1");
					put(grammarAccess.getDeployAppClassTypeAccess().getTypeAssignment_3(), "rule__DeployAppClassType__TypeAssignment_3");
					put(grammarAccess.getDeployAppMasterMethodTypeAccess().getManyAssignment_0(), "rule__DeployAppMasterMethodType__ManyAssignment_0");
					put(grammarAccess.getDeployAppMasterMethodTypeAccess().getNameAssignment_1(), "rule__DeployAppMasterMethodType__NameAssignment_1");
					put(grammarAccess.getDeployAppMasterMethodTypeAccess().getTypeAssignment_3(), "rule__DeployAppMasterMethodType__TypeAssignment_3");
					put(grammarAccess.getDeployAppSlaveMethodTypeAccess().getManyAssignment_0(), "rule__DeployAppSlaveMethodType__ManyAssignment_0");
					put(grammarAccess.getDeployAppSlaveMethodTypeAccess().getNameAssignment_1(), "rule__DeployAppSlaveMethodType__NameAssignment_1");
					put(grammarAccess.getDeployAppSlaveMethodTypeAccess().getTypeAssignment_3(), "rule__DeployAppSlaveMethodType__TypeAssignment_3");
					put(grammarAccess.getMonitorAccess().getNameAssignment_1(), "rule__Monitor__NameAssignment_1");
					put(grammarAccess.getMonitorAccess().getRangeAssignment_3(), "rule__Monitor__RangeAssignment_3");
					put(grammarAccess.getMonitorAccess().getMonitoringTypeAssignment_4(), "rule__Monitor__MonitoringTypeAssignment_4");
					put(grammarAccess.getMonitorRangeTypeAccess().getManyAssignment_0(), "rule__MonitorRangeType__ManyAssignment_0");
					put(grammarAccess.getMonitorRangeTypeAccess().getNameAssignment_1(), "rule__MonitorRangeType__NameAssignment_1");
					put(grammarAccess.getMonitorRangeTypeAccess().getTypeAssignment_3(), "rule__MonitorRangeType__TypeAssignment_3");
					put(grammarAccess.getMonitoringTypeAccess().getManyAssignment_0(), "rule__MonitoringType__ManyAssignment_0");
					put(grammarAccess.getMonitoringTypeAccess().getNameAssignment_1(), "rule__MonitoringType__NameAssignment_1");
					put(grammarAccess.getMonitoringTypeAccess().getTypeAssignment_3(), "rule__MonitoringType__TypeAssignment_3");
					put(grammarAccess.getStressAccess().getNameAssignment_1(), "rule__Stress__NameAssignment_1");
					put(grammarAccess.getStressAccess().getRangeAssignment_3(), "rule__Stress__RangeAssignment_3");
					put(grammarAccess.getStressAccess().getStressClassAssignment_4(), "rule__Stress__StressClassAssignment_4");
					put(grammarAccess.getStressAccess().getStressMethodAssignment_5(), "rule__Stress__StressMethodAssignment_5");
					put(grammarAccess.getStressRangeTypeAccess().getManyAssignment_0(), "rule__StressRangeType__ManyAssignment_0");
					put(grammarAccess.getStressRangeTypeAccess().getNameAssignment_1(), "rule__StressRangeType__NameAssignment_1");
					put(grammarAccess.getStressRangeTypeAccess().getTypeAssignment_3(), "rule__StressRangeType__TypeAssignment_3");
					put(grammarAccess.getStressClassTypeAccess().getManyAssignment_0(), "rule__StressClassType__ManyAssignment_0");
					put(grammarAccess.getStressClassTypeAccess().getNameAssignment_1(), "rule__StressClassType__NameAssignment_1");
					put(grammarAccess.getStressClassTypeAccess().getTypeAssignment_3(), "rule__StressClassType__TypeAssignment_3");
					put(grammarAccess.getStressMethodTypeAccess().getManyAssignment_0(), "rule__StressMethodType__ManyAssignment_0");
					put(grammarAccess.getStressMethodTypeAccess().getNameAssignment_1(), "rule__StressMethodType__NameAssignment_1");
					put(grammarAccess.getStressMethodTypeAccess().getTypeAssignment_3(), "rule__StressMethodType__TypeAssignment_3");
					put(grammarAccess.getActionAccess().getNameAssignment_1(), "rule__Action__NameAssignment_1");
					put(grammarAccess.getActionAccess().getRangeAssignment_3(), "rule__Action__RangeAssignment_3");
					put(grammarAccess.getActionAccess().getClassAssignment_4(), "rule__Action__ClassAssignment_4");
					put(grammarAccess.getActionAccess().getMethodAssignment_5(), "rule__Action__MethodAssignment_5");
					put(grammarAccess.getActionRangeTypeAccess().getManyAssignment_0(), "rule__ActionRangeType__ManyAssignment_0");
					put(grammarAccess.getActionRangeTypeAccess().getNameAssignment_1(), "rule__ActionRangeType__NameAssignment_1");
					put(grammarAccess.getActionRangeTypeAccess().getTypeAssignment_3(), "rule__ActionRangeType__TypeAssignment_3");
					put(grammarAccess.getActionClassTypeAccess().getManyAssignment_0(), "rule__ActionClassType__ManyAssignment_0");
					put(grammarAccess.getActionClassTypeAccess().getNameAssignment_1(), "rule__ActionClassType__NameAssignment_1");
					put(grammarAccess.getActionClassTypeAccess().getTypeAssignment_3(), "rule__ActionClassType__TypeAssignment_3");
					put(grammarAccess.getActionMethodTypeAccess().getManyAssignment_0(), "rule__ActionMethodType__ManyAssignment_0");
					put(grammarAccess.getActionMethodTypeAccess().getNameAssignment_1(), "rule__ActionMethodType__NameAssignment_1");
					put(grammarAccess.getActionMethodTypeAccess().getTypeAssignment_3(), "rule__ActionMethodType__TypeAssignment_3");
					put(grammarAccess.getFeaturesAccess().getNameAssignment_0(), "rule__Features__NameAssignment_0");
					put(grammarAccess.getIntFeatureAccess().getNameAssignment_0(), "rule__IntFeature__NameAssignment_0");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalMyDslParser) parser;
			typedParser.entryRuleDomainModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
