/**
 * generated by Xtext
 */
package org.xtext.example.mydsl.generator;

import com.google.common.collect.Iterables;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;
import org.xtext.example.mydsl.myDsl.Action;
import org.xtext.example.mydsl.myDsl.CloudProvider;
import org.xtext.example.mydsl.myDsl.Create;
import org.xtext.example.mydsl.myDsl.Deploy;
import org.xtext.example.mydsl.myDsl.DeployApp;
import org.xtext.example.mydsl.myDsl.DeployType;
import org.xtext.example.mydsl.myDsl.Monitor;
import org.xtext.example.mydsl.myDsl.Stress;
import org.xtext.example.mydsl.myDsl.VirtualMachine;

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
@SuppressWarnings("all")
public class CopyOfMyDslGenerator implements IGenerator {
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Create> _filter = Iterables.<Create>filter(_iterable, Create.class);
    for (final Create c : _filter) {
      String _name = c.getName();
      String _string = _name.toString();
      String _plus = (_string + ".java");
      String _string_1 = c.toString();
      fsa.generateFile(_plus, _string_1);
    }
    TreeIterator<EObject> _allContents_1 = resource.getAllContents();
    Iterable<EObject> _iterable_1 = IteratorExtensions.<EObject>toIterable(_allContents_1);
    Iterable<Deploy> _filter_1 = Iterables.<Deploy>filter(_iterable_1, Deploy.class);
    for (final Deploy d : _filter_1) {
      String _name_1 = d.getName();
      String _string_2 = _name_1.toString();
      String _plus_1 = (_string_2 + ".java");
      String _string_3 = d.toString();
      fsa.generateFile(_plus_1, _string_3);
    }
    TreeIterator<EObject> _allContents_2 = resource.getAllContents();
    Iterable<EObject> _iterable_2 = IteratorExtensions.<EObject>toIterable(_allContents_2);
    Iterable<VirtualMachine> _filter_2 = Iterables.<VirtualMachine>filter(_iterable_2, VirtualMachine.class);
    for (final VirtualMachine v : _filter_2) {
      String _name_2 = v.getName();
      String _string_4 = _name_2.toString();
      String _plus_2 = (_string_4 + ".java");
      String _string_5 = v.toString();
      fsa.generateFile(_plus_2, _string_5);
    }
    TreeIterator<EObject> _allContents_3 = resource.getAllContents();
    Iterable<EObject> _iterable_3 = IteratorExtensions.<EObject>toIterable(_allContents_3);
    Iterable<CloudProvider> _filter_3 = Iterables.<CloudProvider>filter(_iterable_3, CloudProvider.class);
    for (final CloudProvider cl : _filter_3) {
      String _name_3 = cl.getName();
      String _string_6 = _name_3.toString();
      String _plus_3 = (_string_6 + ".java");
      String _string_7 = cl.toString();
      fsa.generateFile(_plus_3, _string_7);
    }
    TreeIterator<EObject> _allContents_4 = resource.getAllContents();
    Iterable<EObject> _iterable_4 = IteratorExtensions.<EObject>toIterable(_allContents_4);
    Iterable<DeployType> _filter_4 = Iterables.<DeployType>filter(_iterable_4, DeployType.class);
    for (final DeployType dt : _filter_4) {
      String _name_4 = dt.getName();
      String _string_8 = _name_4.toString();
      String _plus_4 = (_string_8 + ".java");
      String _string_9 = dt.toString();
      fsa.generateFile(_plus_4, _string_9);
    }
    TreeIterator<EObject> _allContents_5 = resource.getAllContents();
    Iterable<EObject> _iterable_5 = IteratorExtensions.<EObject>toIterable(_allContents_5);
    Iterable<DeployApp> _filter_5 = Iterables.<DeployApp>filter(_iterable_5, DeployApp.class);
    for (final DeployApp da : _filter_5) {
      String _name_5 = da.getName();
      String _string_10 = _name_5.toString();
      String _plus_5 = (_string_10 + ".java");
      String _string_11 = da.toString();
      fsa.generateFile(_plus_5, _string_11);
    }
    TreeIterator<EObject> _allContents_6 = resource.getAllContents();
    Iterable<EObject> _iterable_6 = IteratorExtensions.<EObject>toIterable(_allContents_6);
    Iterable<Monitor> _filter_6 = Iterables.<Monitor>filter(_iterable_6, Monitor.class);
    for (final Monitor m : _filter_6) {
      String _name_6 = m.getName();
      String _string_12 = _name_6.toString();
      String _plus_6 = (_string_12 + ".java");
      String _string_13 = m.toString();
      fsa.generateFile(_plus_6, _string_13);
    }
    TreeIterator<EObject> _allContents_7 = resource.getAllContents();
    Iterable<EObject> _iterable_7 = IteratorExtensions.<EObject>toIterable(_allContents_7);
    Iterable<Stress> _filter_7 = Iterables.<Stress>filter(_iterable_7, Stress.class);
    for (final Stress s : _filter_7) {
      String _name_7 = s.getName();
      String _string_14 = _name_7.toString();
      String _plus_7 = (_string_14 + ".java");
      String _string_15 = s.toString();
      fsa.generateFile(_plus_7, _string_15);
    }
    TreeIterator<EObject> _allContents_8 = resource.getAllContents();
    Iterable<EObject> _iterable_8 = IteratorExtensions.<EObject>toIterable(_allContents_8);
    Iterable<Action> _filter_8 = Iterables.<Action>filter(_iterable_8, Action.class);
    for (final Action a : _filter_8) {
      String _name_8 = a.getName();
      String _string_16 = _name_8.toString();
      String _plus_8 = (_string_16 + ".java");
      String _string_17 = a.toString();
      fsa.generateFile(_plus_8, _string_17);
    }
  }
}
