/*
* generated by Xtext
*/
package fr.mines_nantes.atlanmod.giraffe.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.mines_nantes.atlanmod.giraffe.services.GiraffeDSLGrammarAccess;

public class GiraffeDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GiraffeDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.mines_nantes.atlanmod.giraffe.parser.antlr.internal.InternalGiraffeDSLParser createParser(XtextTokenStream stream) {
		return new fr.mines_nantes.atlanmod.giraffe.parser.antlr.internal.InternalGiraffeDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GiraffeMetaModel";
	}
	
	public GiraffeDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GiraffeDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
