/*
* generated by Xtext
*/
package fr.mines_nantes.atlanmod.giraffe.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GiraffeDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/mines_nantes/atlanmod/giraffe/parser/antlr/internal/InternalGiraffeDSL.tokens");
	}
}
