/**
 * generated by Xtext
 */
package fr.mines_nantes.atlanmod.giraffe.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class GiraffeDSLDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
