/*
* generated by Xtext
*/
package fr.mines_nantes.atlanmod.giraffe;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GiraffeDSLStandaloneSetup extends GiraffeDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new GiraffeDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

