/*
* generated by Xtext
*/
package fr.mines_nantes.atlanmod.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GiraffeDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.mines_nantes.atlanmod.dsl.ui.internal.GiraffeDSLActivator.getInstance().getInjector("fr.mines_nantes.atlanmod.dsl.GiraffeDSL");
	}
	
}
