/**
 * generated by Xtext
 */
package fr.mines_nantes.atlanmod.giraffe.validation;

import fr.mines_nantes.atlanmod.giraffe.validation.AbstractGiraffeDSLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GiraffeDSLValidator extends AbstractGiraffeDSLValidator {
}
